### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by joshspeagle** [aaryapatil/tapify#7]
Now that there's a fun name in `tapify`, maybe we can think of fun designs for the logo. Not sure if any of us are artistically-inclined or know people who are, but I'm sure there are lots of fun variations that could work here.

**Comment by aaryapatil** [comment]
Two simple ideas for the logo are as follows:
[tapify_logo.pdf](https://github.com/aaryapatil/tapify/files/9409154/tapify_logo.pdf)

Note that this is a first attempt, so there is lots of room for improvement.

**Comment by aaryapatil** [comment]
The second logo is the winner for now. Will update it if I have better ideas later!

**Comment by aaryapatil** [comment]
The second logo is the winner for now. Will update it if I have better ideas later!
